[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ansem_fight = "F9ufrD6qJ87S5uhhCHPJa6jcrP5DCo3Gdn11hFvj3cef"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
